import { Component, OnInit } from '@angular/core';

declare var $: any;
declare var initVizEconomicos;
// declare var vez;

@Component({
  selector: 'app-economicos',
  templateUrl: './economicos.component.html',
  styleUrls: ['./economicos.component.css']
})
export class EconomicosComponent implements OnInit {
  DesPro = 'Recogida de residuos';
  datos;

opcionSeleccionada: string = '0';
verSeleccion: string = '';
vez:number = 0;

  constructor() {


    this.datos =
    [
      'A Diputaciones',
      'A EMUVIJESA-Gestión urbanistica',
      'A Entidades Locales Autónomas',
      'A la Administración General del Estado',
      'A otras entidades agrupen municipios',
      'Acción social',
      'Act. prog prev mendicidad inf.',
      'Activ. Día Mundial Discapacidad',
      'Activ.menores p. Infanc Fam.',
      'Actividades convivencia intercultural',
      'Actividades Culturales en barriadas rurales',
      'Actividades culturales y deportivas',
      'Actividades de Juventud',
      'Actividades Institucionales',
      'Actividades programa participación y solidaridad',
      'Actuaciones consolidación Palacio Villapanes',
      'Actuaciones inmediatas',
      'Actuaciones PMS- Cerrofruto',
      'Actuaciones varias',
      'Actuaciones varias en Claustros de Santo Domingo',
      'Adecuacion espacios libres calle Taxdirt',
      'Adecuación espacios públicos entorno centro comerc. Area Sur',
      'Adquisicion maquinaria',
      'Adquisicion material de transporte',
      'Agua',
      'AJEMSA- Serv. agua',
      'Alumbrado decorativo fiestas',
      'Amortización prestamos a medio y largo entes fuera sector público',
      'Arrendamiento de maquinaria',
      'Arrendamiento material transporte',
      'Arrendamiento otro inmovilizado material',
      'Arrendamientos de equipos para proceso de informacion',
      'Arrendamientos de mobiliario y enseres',
      'Arrendamientos edificios y otras construcciones',
      'Atencion a la ciudadania en distritos',
      'Atencion sociales en interes de la ciudad',
      'Atenciones benéf. y asistenc',
      'Atenciones protocolarias y representativas',
      'Ayuda domiciliaria- limpieza y aseo',
      'Ayudas a banda de música',
      'Ayudas a Bono-Taxi',
      'Balizamiento y B.R.V.',
      'Campaña contra la violencia de género',
      'Canalizaciones via pública',
      'Cánones',
      'Centro acogida inmigrant(CEAIN)',
      'CIRJESA-Circuito de Jerez',
      'CIRJESA-Circuito de Jerez',
      'Climatizacion de instalaciones',
      'Club Amigos del Zoo',
      'Colegio Oficial Veterinarios de Cádiz',
      'Combustibles y carburantes',
      'Comedor el Salvador',
      'Complemento destino personal funcionario',
      'Complemento específico personal funcionario',
      'COMUJESA',
      'Comunidad de propietarios',
      'Consejo Económico y Social',
      'Conservación señalización horizontal',
      'Conservacion y mantenimiento en mercado central de abastos',
      'Conservación y mantenimiento planta compostaje y reciclaje',
      'Consorcio Bomberos Provincia Cádiz',
      'Consorcio Metropolitano Transporte Bahia Cádiz',
      'Consorcio Metropolitano Transporte Bahía Cádiz',
      'Control tarjetas O.R.A.',
      'Convocatoria unica de subvenciones',
      'Cruz Roja Jerez (UMES)',
      'Custodia',
      'Del personal directivo',
      'Del personal no directivo',
      'Dietas del personal directivo',
      'Dietas del personal no directivo',
      'Dietas miembros de los organos de gobierno',
      'Dinamizacion asociaciones',
      'EDUSI',
      'EMEMSA-Montes de Propios',
      'EMUVIJESA-Promoción y Gestión de vivienda oficial',
      'Energía eléctrica',
      'Equipo fotografico digital',
      'Equipos para procesos de información',
      'Escuela Negocios de Jerez',
      'Estudios y trabajos técnicos',
      'Festejos populares',
      'Fondo Contingencia de Ejecución Presupuestaria (Art.31 LOEPSF)',
      'Fondo estatatal para el empleo y sostenibilidad local',
      'Formación y perfeccionamiento del personal',
      'Fundación Andrés de Ribera',
      'Fundación Caballero Bonald',
      'Fundacion centro acogida San Jose',
      'Fundación Centro Acogida San José',
      'Fundación Municipal de Formación y Empleo',
      'Fundación Secretariado General Gitano',
      'Fundación Teatro Villamarta',
      'Fundaciones',
      'Gastos diversos',
      'Gastos diversos proyecto casa mujeres',
      'Gastos en aplicaciones informáticas',
      'Gastos formaliza.',
      'Gest. ayudas sociales especie',
      'Gratificaciones',
      'Grupo desarrollo rural',
      'Horas extraordinarias personal laboral fijo',
      'Indefinidos no fijos en plantilla',
      'Indemnizaciones',
      'Informáticas',
      'Instalación areas de recreo infantil en diferentes zonas de Jerez',
      'Instalacion de circuitos biosaludables en espacios públicos',
      'Intereses de demora',
      'Intereses préstamo interior',
      'Inversión',
      'Inversiones en Instalaciones y pistas',
      'JECOMUSA-Servicio de radio y television Municipal',
      'JEREYSSA-Servicio de Recaudación',
      'JESYTEL-Servic Informaticos Internos',
      'Jurídicos',
      'Limpieza Colegios Públicos',
      'Limpieza dependencias municipales',
      'Limpieza y aseo',
      'Locomocion de miembros organos gobierno',
      'Mancomunidad municipios Bahía Cádiz',
      'Mantenimiento alarmas',
      'Mantenimiento alumbrado público',
      'Mantenimiento de fuentes ornamentales',
      'Mantenimiento de parques infantiles',
      'Mantenimiento extintores',
      'Mantenimiento parques y jardines públicos',
      'Mantenimiento Red Semafórica',
      'Mantenimiento señalización horizontal',
      'Mantenimiento señalización vertical',
      'Mantenimiento y alquiler w.c. botellodromo',
      'Manutención de animales.',
      'Maquinaria',
      'Material informático no inventariable',
      'Mobiliario y enseres',
      'Obras Plan Urban',
      'Operaciones de intercambio financiero',
      'Ordinario no inventariable',
      'Ordinario no inventariable para almacen',
      'Otras indemnizaciones',
      'Otras inversiones en infraestructuras',
      'Otras inversiones nuevas en infraestructuras y bienes para u',
      'Otras inversionesnuevas asociadas funcionamiento operativo servicio',
      'Otras remuneraciones',
      'Otras remuneraciones personal eventual-Grupos Políticos',
      'Otras remuneraciones personal laboral fijo',
      'Otras subvenciones a empresas privadas',
      'Otras transferencias',
      'Otras transferencias de capital',
      'Otros complementos personal funcionario',
      'Otros gastos de promocion',
      'Otros gastos diversos',
      'Otros gastos en comunicaciones',
      'Otros gastos financieros',
      'Otros suministros',
      'Otros trabajos realizados por otras empresas y profesionales',
      'Parque flotante desmontable',
      'Patronato Municipal Parque Zoológico',
      'Plan Promoción de Empleo',
      'Por obras a cargo de terceros',
      'Postales',
      'Postales',
      'Premios',
      'Prensa',
      'Primas de seguro',
      'Productividad',
      'Productos alimenticios',
      'Productos de limpieza y aseo',
      'Productos farmaceut y mater sanitario',
      'Programa individual atención',
      'Programa municipal prevención acciones',
      'Programa plan zona sur no subvencionado',
      'Programa subvencionado znts',
      'Programa transf. ',
      'Programa voluntariado',
      'Programas actuacion en distritos',
      'Proyecto salud nuestra ciudad',
      'Publicación en Diarios Oficiales',
      'Publicidad y propaganda',
      'Publicidad',
      'Recogida de residuos urbanos',
      'Reforma de infraestructuras en barriada ICOVESA',
      'Rehabilitacion techos de galeria soportales de Madre de Dios',
      'Reparacion edificio gimnasio Campo de la Juventud',
      'Reparación, mantenimiento y conservación aparatos aire acondicionado',
      'Reparación, mantenimiento y conservación edificios y otras construcciones',
      'Reparación, mantenimiento y conservación elementos transporte',
      'Reparación, mantenimiento y conservación elevadores',
      'Reparación, mantenimiento y conservación emisoras radio',
      'Reparación, mantenimiento y conservación equipos proceso informatico',
      'Reparación, mantenimiento y conservación infraestr.y bienes nat.',
      'Reparación, mantenimiento y conservación maquinaria, instalaciones y utillaje',
      'Reparación, mantenimiento y conservación mobiliario y enseres',
      'Reparación, mantenimiento y conservación otro inmovilizado material',
      'Resarcimiento esfuerzo electrico IKEA',
      'Resto de adquisiciones de acciones del sector publico',
      'Retrib.basicas personal laboral fijo',
      'Retribuciones básicas personal eventual-Grupos Políticos',
      'Retribuciones básicas y otras remuneraciones ',
      'Retribuciones complementarias-Grupos Políticos',
      'Retribuciones en especie-Otras prestaciones económicas a fav',
      'Retribuciones otro personal',
      'Retribuciones personal laboral eventual',
      'Reuniones',
      'Reurbanizacion parque forestal La Marquesa',
      'Seguridad',
      'Seguridad Social',
      'Seguros voluntario P.C.',
      'Seguros-Otras prestaciones económicas a favor de empleados',
      'Servicio atención de día infantil y juvenil',
      'Servicio transporte autobuses a pedanias',
      'Servicios de recaudación a favor de la entidad',
      'Servicios Técnicos (Veterinario',
      'Speed Festival',
      'Subvección deficit transporte colectivo urbano',
      'Subvención al Taxi accesible',
      'Subvención empresas privadas para fomento empleo',
      'Sueldos del grupo A1 personal funcionario',
      'Sueldos del grupo A2 personal funcionario',
      'Sueldos del Grupo C1',
      'Sueldos del grupo c2 personal funcionario',
      'Sueldos del Grupo E',
      'Sum.repuestos maquinaria',
      'Suminist otro material para almacen central',
      'Suministro de gas-Serv.Grales.Deportes',
      'Suministro de vestuario.',
      'Suministro munición',
      'Teleasistencia domiciliaria',
      'Telegráficas',
      'Terrenos y bienes naturales-Actuaciones PMS',
      'Transf.capital a familias e instit.sin fines lucro',
      'Transf.capital Archic. Stmo.Cristo Expiración Ermita S.Telmo',
      'Transf.capital Hermandad La Sentencia Rehab.Ermita La Yedra-',
      'Transf.capital Orden Padres Mercedarios Reh.Basílica Merced-',
      'Transferencias a Ayuntamientos',
      'Transportes de mercancías',
      'Tributos Comunidades Autónomas',
      'Tributos de las Entidades locales',
      'Tributos estatales',
      'Trienios personal funcionario',
      'Urbanizacion de entorno de San Juan de los Caballeros',
      'Urbanizacion de parcela edificio Jefatura de Policia Local',
      'Valoraciones y peritajes'
      ]
    
    ;
      }

 capturar() {
      this.verSeleccion = this.opcionSeleccionada;
      this.vez += 1;
      console.log('Vez =' + this.vez);
      initVizEconomicos(this.verSeleccion, this.vez);
         }

  ngOnInit() {
  
  }

}
