import { Component, OnInit } from '@angular/core';

declare var $: any;
// declare var viz;
// declare var tableau;
declare var initVizEconomicos;

@Component({
  selector: 'app-economicos',
  templateUrl: './economicos.component.html',
  styleUrls: ['./economicos.component.css']
})
export class EconomicosComponent implements OnInit {
datos;
vez = 0;

  constructor() {
    this.datos =
    [
      'A CIRJESA-Circuito de Jerez',
      'A Diputaciones, Consejos y cabildos',
      'A EMUVIJESA-Gestión urbanistica',
      'A Entidades Locales Autónomas',
      'A la Administración General del Estado',
      'A la administracióngeneral de las Comunidades Autónomas',
      'A otras entidades agrupen municipios',
      'A otros subsectores',
      'A/C RESTAUR. Y REHABILIT.SALA PROFUNDIS CLAUSTRO ST.DOMINGO',
      'Acción social',
      'Actividades complementarias',
      'Actividades convivencia intercultural',
      'Actividades culturales en barriadas rurales',
      'Actividades culturales y deportivas',
      'Actividades de juventud',
      'Actividades Día Mundial Discapacidad',
      'Actividades Institucionales',
      'Actividades menores p. Infanc Fam.',
      'Actividades programa participación y solidaridad',
      'Actividades programa prevención mendicidad infantil',
      'Actuaciones consolidación Palacio Villapanes',
      'Actuaciones en El Alcazar',
      'Actuaciones en piscina municipal ELA Torrecera',
      'Actuaciones inmediatas',
      'Actuaciones medioambientales Cementerio Municipal',
      'Actuaciones PMS- Cerrofruto',
      'Actuaciones varias',
      'Actuaciones varias en Claustros de Santo Domingo',
      'Adecentamiento de vías públicas ELA Estella del Marqués',
      'Adecuacion espacios libres calle Taxdirt',
      'Adecuación espacios públicos entorno centro comerc. Area Sur',
      'Adquisición elementos de transporte',
      'Adquisición equipo informatico',
      'Adquisición equipos análisis',
      'Adquisicion maquinaria, instalaciones y utillaje',
      'Adquisicion material de transporte',
      'ADQUISICIONES EN DELIMITACIONES DE AREAS',
      'Agua',
      'AJEMSA- Serv. agua, alcantarillado y recogida de residuos',
      'Al exterior',
      'Alumbrado decorativo fiestas',
      'Alumbrado decorativo Navidad',
      'Amortización prestamos a medio y largo entes fuera sector público',
      'Amortización prestamos largo plazo entes sector público',
      'Anctuaciones en aseos CEIP Guadalete ELA El Torno',
      'Anticipos reintegros al personal a largo plazo',
      'Anticipos reintegros al personal a largo plazo',
      'Arrendamiento de maquinaria, instalaciones y utillaje',
      'Arrendamiento material transporte',
      'Arrendamiento otro inmovilizado material',
      'Arrendamientos de equipos para proceso de informacion',
      'Arrendamientos de mobiliario y enseres',
      'Arrendamientos edificios y otras construcciones',
      'Asociación de Ciudades Interculturales',
      'Atencion a la ciudadania en distritos',
      'Atencion sociales en interes de la ciudad',
      'Atenciones benéficiencia y asistencia',
      'Atenciones protocolarias y representativas',
      'Ayuda domiciliaria',
      'Ayudas a banda de música',
      'Ayudas a Bono-Taxi',
      'Ayudas sociales alquiler',
      'Balizamiento y B.R.V.',
      'Banco de alimentos',
      'Cambio luminaria pública a LED piscina mpal. ELA El Torno',
      'Campaña contra la violencia de género',
      'CAMPO DE FUTBOL 7 BDA. LA GRANJA',
      'Canalizaciones vía pública',
      'Cánones',
      'CARGAS URBANISTICAS',
      'Centro acogida inmigrantes (CEAIN)',
      'Centro de Arte Contemporáneo Callejón de los Bolos',
      'Centro de día Hogar San Juan',
      'CIRJESA-Circuito de Jerez',
      'CLAUSTROS DE SANTO DOMINGO',
      'Climatizacion de instalaciones',
      'Club Amigos del Zoo',
      'Colegio Oficial Veterinarios de Cádiz',
      'Combustibles y carburantes',
      'Comedor el Salvador',
      'Complemento destino personal funcionario',
      'Complemento específico personal funcionario',
      'COMUJESA',
      'Comunidad de propietarios',
      'CONEXION CON SISTEMA GRAL VIARIO U.E. 2Q1 ARROYO MEMBRILLAR',
      'Consejo Económico y Social',
      'Conservación señalización horizontal, vertical y baliz.',
      'Conservacion y mantenimiento en mercado central de abastos',
      'Conservación y mantenimiento planta compostaje y reciclaje',
      'Consorcio Bomberos Provincia Cádiz',
      'Consorcio Metropolitano Transporte Bahia Cádiz',
      'Consorcio Metropolitano Transporte Bahía Cádiz',
      'CONSTRUCCION DE CENTRO EUROPEO DE LA MUSICA ANDALUSI',
      'CONSTRUCCION DE GLORIETA EN A-4 ACCESOS AL SECTOR SUP 34',
      'Control tarjetas O.R.A.',
      'Contrucción nave cobertizo instalaciones deportivas San Isidro',
      'Convenio AFEMEN',
      'Convenio APESORJE',
      'Convocatoria unica de subvenciones',
      'Coordinadora ONGDS de la provincia de Cádiz',
      'Cruz Roja Jerez (UMES)',
      'Cruz Roja -Transporte',
      'Custodia, depósito y almacenaje',
      'Del personal directivo',
      'Del personal no directivo',
      'Dietas del personal directivo',
      'Dietas del personal no directivo',
      'Dietas miembros de los organos de gobierno',
      'Dinamización asociaciones',
      'Dinamización del ocio juvenil',
      'Ecomercado',
      'Economato San Juan de Dios',
      'Edificios y otras construcciones',
      'EDUSI',
      'Ejecución aval UE 4G4B Pago Perceba',
      'EMEMSA-Montes de Propios',
      'EMUVIJESA-Promoción y Gestión de vivienda oficial',
      'Energía eléctrica',
      'Equipamiento Sala Paúl',
      'Equipo fotografico digital',
      'Equipos para procesos de información',
      'Escuela Negocios de Jerez',
      'ESCULTURA ROTONDA DE CUATRO CAMINOS',
      'Estudios y trabajos técnicos',
      'Expediente Reparcelación de la U.E. 4.A.4 ',
      'Expediente Reparcelación de la U.E. 4.S.2 ',
      'Expediente Reparcelación de la U.E. 4.S1 ',
      'Expropiación forz. Poligono 4 PAU 1 Fdo. Portillo',
      'Festejos populares',
      'Fondo compensación ELA por crecimiento habitantes desde convenio vigente',
      'Fondo Contingencia de Ejecución Presupuestaria (Art.31 LOEPSF)',
      'Fondo estatatal para el empleo y sostenibilidad local',
      'Formación y perfeccionamiento del personal',
      'Fundación Andrés de Ribera',
      'Fundación Caballero Bonald',
      'Fundacion centro acogida San Jose',
      'Fundación Centro Acogida San José',
      'Fundación Municipal de Formación y Empleo',
      'Fundación Secretariado General Gitano',
      'Fundación Teatro Villamarta',
      'Fundaciones',
      'Fundarte ',
      'Gastos diversos',
      'Gastos diversos proyecto casa mujeres',
      'Gastos en aplicaciones informáticas',
      'Gastos formalización,modificación y cancelación operaciones en euros',
      'Gestion ayudas sociales especie',
      'Gratificaciones',
      'Grupo desarrollo rural',
      'Horas extraordinarias personal laboral fijo',
      'Indefinidos no fijos en plantilla',
      'Indemnizaciones',
      'Indemnizaciones ERE',
      'Informáticas',
      'Instalación areas de recreo infantil en diferentes zonas de Jerez',
      'Instalación cesped artifical campo futbol Picadueñas',
      'Instalacion de circuitos biosaludables en espacios públicos',
      'INSTALACION MAQUINARIA AIRE ACONDICIONADO CASA MUJER II FASE',
      'Intereses de demora',
      'Intereses de demora a acreedores públicos',
      'Intereses de demora a acreedores públicos otros',
      'Intereses préstamo interior',
      'Inv.asociadas a actuaciones urbanísticas',
      'Inversión, reposición edificios y otras construcciones',
      'Inversiones en Instalaciones y pistas',
      'JECOMUSA-Servicio de radio y television Municipal',
      'JEREYSSA-Servicio de Recaudación',
      'JESYTEL-Servic Informaticos Internos',
      'Jurídicos, contenciosos',
      'Limpieza Colegios Públicos',
      'Limpieza dependencias municipales',
      'Limpieza y aseo',
      'Locomocion de miembros organos gobierno',
      'Mancomunidad municipios Bahía Cádiz',
      'Mantenimiento alarmas',
      'Mantenimiento alumbrado público',
      'Mantenimiento de fuentes ornamentales',
      'Mantenimiento de parques infantiles',
      'Mantenimiento extintores',
      'Mantenimiento parques y jardines públicos',
      'Mantenimiento Red Semafórica',
      'Mantenimiento señalización horizontal',
      'Mantenimiento señalización vertical',
      'Mantenimiento y alquiler WC botellodromo',
      'Manutención de animales.',
      'Maquinaria, instalaciones y utillaje',
      'Material informático no inventariable',
      'Mejoras alumbrado público ELA Estella del Marqués',
      'Mobiliario y enseres',
      'MUSEO DE LA CIUDAD DE JEREZ',
      'OBRAS ACCESIBILIDAD 2005. CONVENIO IMSERSO Y ONCE',
      'Obras de urbanización calle C - UE 4Q1 ',
      'Obras Fondo Estatal de Inversión Local',
      'Obras P.O.S.',
      'Obras Plan Urban',
      'Operaciones de intercambio financiero',
      'Ordenanzas Reg. Fomento desarrollo económico Jerez',
      'Ordinario no inventariable',
      'Ordinario no inventariable para almacen',
      'Otras indemnizaciones',
      'Otras inversiones de reposición asociadas al funcionamiento operativo',
      'Otras inversiones en infraestructuras',
      'Otras inversiones financ.con ejecución avales',
      'Otras inversiones nuevas en infraestructuras y bienes para u',
      'Otras inversionesnuevas asociadas funcionamiento operativo servicio',
      'OTRAS OBRAS CONEXION NORTE',
      'Otras remuneraciones',
      'Otras remuneraciones personal eventual-Grupos Políticos',
      'Otras remuneraciones personal laboral fijo',
      'Otras subvenciones a empresas privadas',
      'Otras subvenciones a entes públicos y sociedades mercantiles',
      'Otras transferencias',
      'Otras transferencias de capital',
      'Otros complementos personal funcionario',
      'Otros gastos de promoción',
      'Otros gastos diversos',
      'Otros gastos en comunicaciones',
      'Otros gastos financieros',
      'Otros suministros',
      'Otros trabajos realizados por otras empresas y profesionales',
      'Parque flotante desmontable',
      'Patronato Municipal Parque Zoológico',
      'Plan de actuación en colegios pedanias',
      'Plan Especial San Juan de Dios',
      'Plan Promoción de Empleo',
      'Por obras a cargo de terceros',
      'POS 2006 Asfaltado varias calles en Nueva Jarilla',
      'Postales',
      'Postales otras',
      'Premios, becas y pensiones de estudio',
      'Prensa, revistas, libros y otras publicaciones',
      'Presupuestos participativos pendientes ejecución anterior',
      'Primas de seguro',
      'Productividad',
      'Productos alimenticios',
      'Productos de limpieza y aseo',
      'Productos farmaceuticos y material sanitario',
      'Programa individual atención',
      'Programa municipal prevención acciones',
      'Programa plan zona sur no subvencionado',
      'Programa subvencionado zonas',
      'Programa transf. ',
      'Programa voluntariado',
      'Programas actuacion en distritos',
      'Proyecto Hombre',
      'Proyecto salud nuestra ciudad',
      'PROYECTOS MODIFICADOS Y LIQUIDACIONES OBRAS CONVENIO EDUCACI',
      'Publicación en Diarios Oficiales',
      'Publicidad y propaganda',
      'Publicidad, propaganda a cargo particulares',
      'Puesta en valor del Cine Astoria',
      'Recogida de residuos urbanos',
      'Reforma de infraestructuras en barriada ICOVESA',
      'Refuerzo de firme varias calles',
      'Rehabilitación piscina municipal ELA Torrecera',
      'Rehabilitacion techos de galeria soportales de Madre de Dios',
      'Rehabilitacion y mejoras parque y pistal padel ELA La Barca',
      'Rehabilitacion y mejoras zonas deportivas ELA San Isidro',
      'Rehabilitacioón centro cultural ELA Estella del Marqués',
      'Remodelacion edificio junto estacion tren (imprenta municipal)',
      'REMODELACION VIAL GLORIETA CUATRO CAMINOS CON NUDO ENLACE N-',
      'Reordenación de Plaza Belén',
      'Reparacion edificio gimnasio Campo de la Juventud',
      'Reparación mantenimiento y conservación instrumentos municipales',
      'Reparación saneamiento vía pública ELA Guadalcacin',
      'Reparación sistema electronio campo futbol ELA Guadalcacin',
      'Reparación, mantenimiento y conservación aparatos aire acondicionado',
      'Reparación, mantenimiento y conservación edificios y otras construcciones',
      'Reparación, mantenimiento y conservación elementos transporte',
      'Reparación, mantenimiento y conservación elevadores',
      'Reparación, mantenimiento y conservación emisoras radio',
      'Reparación, mantenimiento y conservación equipos proceso informático',
      'Reparación, mantenimiento y conservación infraestructura y bienes naturales',
      'Reparación, mantenimiento y conservación maquinaria, instalaciones y utillaje',
      'Reparación, mantenimiento y conservación mobiliario y enseres',
      'Reparación, mantenimiento y conservación otro inmovilizado material',
      'Resarcimiento esfuerzo electrico IKEA',
      'Resto de adquisiciones de acciones del sector publico',
      'Retribuciones básicas personal eventual-Grupos Políticos',
      'Retribuciones básicas personal laboral fijo',
      'Retribuciones básicas y otras remuneraciones ',
      'Retribuciones complementarias-Grupos Políticos',
      'Retribuciones en especie',
      'Retribuciones otro personal',
      'Retribuciones personal laboral eventual',
      'Reuniones, conferencias y cursos',
      'REURB. C/CANTARERIA Y C/NUEVA (ACTUACIONES BARRIO SANTIAGO)',
      'Reurbanizacion parque forestal La Marquesa',
      'Sector 30 San José Obrero',
      'Seguridad',
      'Seguridad Social',
      'Seguros voluntario P.C.',
      'Seguros-Otras prestaciones económicas a favor de empleados',
      'Servicio atención de día infantil y juvenil',
      'Servicio transporte autobuses a pedanias',
      'Servicios de recaudación a favor de la entidad',
      'Servicios Técnicos (Veterinario, herrador,etc)',
      'Speed Festival',
      'Subvección deficit transporte colectivo urbano',
      'Subvención al Taxi accesible',
      'Subvención empresas privadas para fomento empleo',
      'Sueldos del grupo A1 personal funcionario',
      'Sueldos del grupo A2 personal funcionario',
      'Sueldos del Grupo C1',
      'Sueldos del grupo C2 personal funcionario',
      'Sueldos del Grupo E',
      'Suminist otro material para almacen central',
      'Suministro de gas',
      'Suministro de vestuario.',
      'Suministro material electrónico, eléctrico y telecomunicaciones',
      'Suministro munición',
      'Suministro repuestos maquinaria, utillaje y elementos',
      'Tabanco del Duque',
      'Teleasistencia domiciliaria',
      'Telegráficas',
      'Terrenos y bienes naturales',
      'Terrenos y bienes naturales-Actuaciones PMS',
      'Transf.capital a familias e instit.sin fines lucro',
      'Transferencia capital Archic. Stmo.Cristo Expiración Ermita S.Telmo',
      'Transferencia capital Hermandad La Sentencia Rehab.Ermita La Yedra',
      'Transferencia capital Orden Padres Mercedarios Reh.Basílica Merced',
      'Transferencias a Ayuntamientos',
      'Transferencias a entidades',
      'Transportes de mercancías',
      'Tributos Comunidades Autónomas',
      'Tributos Entidades locales',
      'Tributos Estatales',
      'Trienios personal funcionario',
      'Urbanización ARI F-05- La Hoyanca',
      'Urbanización Calle Varsovia',
      'Urbanizacion de entorno de San Juan de los Caballeros',
      'Urbanizacion de parcela edificio Jefatura de Policia Local',
      'URBANIZACION U.E. 1A18 MERCED',
      'URBANIZACION U.E. 4K1 Y 2M EL ANGEL (C/ATLANTA Y EJE)',
      'URBANIZACION U.E. 4S2 SAN JERONIMO B - 1ª FASE',
      'Urbanización UE 2T1 Armas de Santiago',
      'URBANIZACION VIAL ENTRE UE 2T1 ARMAS SANTIAGO Y 1A18 MERCED',
      'Valoraciones y peritajes',
    ]
    ;
      }

   ngOnInit() {
    $(function () {
        const configChosen = {
        '.chosen-select': {},
      };

      $('.chosen-select').chosen({
        disable_search_threshold: 10,
        no_results_text: 'No encuentro ',
        // width: '65%',
       });

    });

    let vez = 0;
    $('#chosen1').change(function () {
      vez += 1;
      initVizEconomicos($(this).val(), vez);
         });
   }
}

// function initVizEconomicos(DesEco, vez) {
//     if (vez > 1) {
//       viz.dispose();
//     }
//     const containerDiv = document.getElementById('vizContainerEconomicos'),
//       // C:\Users\pc\Google Drive\Ayuntamiento\Presupuestos\2.018\Ejecucion\2018.10.01
//       urlEconomicos = 'https://public.tableau.com/views/1EstadoEjecucin2018Gastosporaplicaciones1-10-2018MAM/Economicoporprogramas?:embed=y&:display_count=yes&publish=yes',
//       options = {
//         'DesEco': DesEco,
//         hideTabs: true,
//         showShareOptions: true
//       };
//     viz = new tableau.Viz(containerDiv, urlEconomicos, options);
//   }
